env:
  - NOT_CRAN=TRUE _R_CHECK_LENGTH_1_LOGIC2_=TRUE

language: r

sudo: false

cache: packages

r_packages:
  - covr

branches:
  only:
    - master
    - development
    - rc

after_success:
  - Rscript covr.R

matrix:
  include:
    - r: 3.1
      if: branch = rc
    - r: 3.2
      if: branch = rc
    - r: 3.3
      if: branch = rc
    - r: oldrel
      if: branch = rc
    - r: release
    - r: devel
